Education/Models/Instructor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;

namespace Education.Models
{
    public class Instructor
    {
        public int Id { set; get; }
        [MinLength(3)]
        public string Name { set; get; }
        [EmailAddress(ErrorMessage = "Invalid email address")]
        public string Email { set; get; }
        [RegularExpression("^[0-9]{7,11}$", ErrorMessage = "Please enter a valid Phone number.")]
        [MinLength(7)]
        public string Phone { set; get; }
        public string? Address { set; get; }

        [DataType(DataType.Password)]
        public string Password { set; get; }

        [Compare("Password")]
        [NotMapped]
        [DataType(DataType.Password)]
        public string confirmPassword { get; set; }

        [Range(15, 100)]
        public int? Age { set; get; }
        [Column(TypeName = "image")]
        
        public byte[]? image { set; get; }

        //public IFormFile ImageFile;

        public bool Isdeleted { set; get; }

        [ForeignKey("role")]
        public int RoleId { set; get; }
        public virtual Role? role { set; get; }
        public virtual List<Topic>? Topic { get; set; } = new List<Topic>();
        public virtual List<Instructor_Student>? instructorStudents { set; get; } = new List<Instructor_Student>();
        public virtual List<StudentRequests>? StudentRequests { set; get; } = new List<StudentRequests>();

    }
}

Education/Controllers/InstructorController.cs
using Education.Models;
using Education.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
//using Microsoft.Web.Helpers;
using Newtonsoft.Json;
using System.Buffers.Text;
using System.Data;
using System.Security.Claims;
using System.Security.Principal;

namespace Education.Controllers
{
    public class InstructorController : Controller
    {
        IInstructorService _InstructorService = null;
        private readonly IRoleService _RoleService;

        public InstructorController(IInstructorService instructorService, IRoleService RoleService)
        {
            //instructorGeneric = instructor;
            this._InstructorService = instructorService;
            _RoleService = RoleService;

        }
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var userIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            int Id = int.Parse(userIdClaim.Value);
            IEnumerable<Instructor> instructors = _InstructorService.GetAll().Where(instructor => instructor.Id != Id);
            return View(instructors);
        }

        public IActionResult ShowImage()
        {
            var userIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            int Id = int.Parse(userIdClaim.Value);
            var currInstructor = _InstructorService.GetById(Id);
            if (currInstructor?.image?.Length > 0 && currInstructor?.image != null)
            {
                string base64Image = Convert.ToBase64String(currInstructor.image);
                string imageSrc = $"data:image/jpeg;base64,{base64Image}";
                return PartialView("_ImagePartial", imageSrc);
            }
            return PartialView("_ImagePartial", "/img/undraw_profile.svg");


        }
        [Authorize(Roles = "Admin")]
        IActionResult getRoleByInstructor(Instructor instructor)
        {
            Role roles = _RoleService.GetById(instructor.RoleId);
            return Json(roles);

        }
        [Authorize(Roles = "Admin")]
        public IActionResult New()
        {
            ViewData["RoleList"] = _RoleService.GetAll();
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult New(Instructor _instructor, IFormFile ? image)
        {
            if (ModelState.IsValid == true)
            {
                try
                {
                    if (image != null && image.Length > 0)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            image.CopyTo(memoryStream);
                            _instructor.image = memoryStream.ToArray();
                        }
                    }
                    _instructor.Password = BCrypt.Net.BCrypt.HashPassword(_instructor.Password);
                    _instructor.Isdeleted = false;


                    _InstructorService.Insert(_instructor);
                    _InstructorService.Save();
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            ViewData["RoleList"] = _RoleService.GetAll();
            return View(_instructor);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Save(Instructor _instructor, IFormFile imageFile)
        {
            if (ModelState.IsValid == true)
            {

                if (imageFile != null && imageFile.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        imageFile.CopyTo(memoryStream);
                        _instructor.image = memoryStream.ToArray();
                    }
                }
                //
                _instructor.Password = BCrypt.Net.BCrypt.HashPassword(_instructor.Password);
                _instructor.Isdeleted = false;


                _InstructorService.Insert(_instructor);

                _InstructorService.Save();
                return RedirectToAction("Index");
            }
            return View("New", _instructor);
        }
        [Authorize]
        public IActionResult Edit(int id)
        {
            Instructor instructor = _InstructorService.GetById(id);
            ViewData["RoleList"] = _RoleService.GetAll();
            ViewBag.EncryptedPassword = instructor.Password;
            return View(instructor);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Edit(Instructor instructor, IFormFile? imageFile)
        {
            try
            {


                ModelState.Remove("ConfirmPassword");
                ModelState.Remove("Password");
                if (ModelState.IsValid == true)//Server Side Check
                {

                    var userIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
                    int Id = int.Parse(userIdClaim.Value);
                    string password = _InstructorService.GetById(Id).Password;
                    instructor.Password = password;
                    var StoredInstructor = _InstructorService.GetByIdAsNoTracking(Id);

                    if (imageFile != null && imageFile.Length > 0)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            imageFile.CopyTo(memoryStream);
                            instructor.image = memoryStream.ToArray();
                        }
                    }
                    else
                    {
                        instructor.image = StoredInstructor.image;

                    }



                    if (instructor.RoleId == 0)
                    {
                        instructor.RoleId = StoredInstructor.RoleId;
                    }

                    _InstructorService.Update(instructor);

                    if (instructor.RoleId != StoredInstructor.RoleId)
                    {

                        // Retrieve the current user's claims identity and create a new claims principal
                        ClaimsIdentity identity = (ClaimsIdentity)User.Identity;

                        // Locate the existing claim for the role
                        Claim existingRoleClaim = identity.FindFirst(ClaimTypes.Role);

                        // Remove the existing role claim
                        identity.RemoveClaim(existingRoleClaim);

                        // Add the updated role claim

                        identity.AddClaim(new Claim(ClaimTypes.Role, _RoleService.GetById(instructor.RoleId).Name));


                        ClaimsPrincipal principal = new ClaimsPrincipal(identity);



                        // Sign in the user with the updated claims principal
                         HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);




                    }
                    if (Id == instructor.Id)
                    {
                        return RedirectToAction("Profile", "Account");
                    }


                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.InnerException.Message);
            }
            ViewData["RoleList"] = _RoleService.GetAll();
            return View(instructor);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            _InstructorService.Delete(id);
            return RedirectToAction("Index");

        }
    }

}

Education/Views/Instructor/Edit.cshtml
@using Education.Models
@model Instructor
@{
    ViewData["Title"] = "Edit";
    SelectList roleItems = new SelectList(ViewBag.RoleList, "Id", "Name");
}
<div class="main-panel">
    <form method="post" asp-action="Edit" asp-controller="instructor" enctype="multipart/form-data">
        <div>
            <label asp-for="Name"></label>
            <input class="form-control" asp-for="Name" />
        </div>
        <div>
            <label asp-for="Email"></label>
            <input class="form-control" asp-for="Email" />
        </div>
        <div>
            <label asp-for="Phone"></label>
            <input class="form-control" asp-for="Phone" />
        </div>
        <div>
            <label asp-for="Address"></label>
            <input class="form-control" asp-for="Address" />
        </div>
        <div>
            <label asp-for="image"></label>
            <input id="fileInput" type="file" class="form-control mb-3" name="imageFile" />
            @if (@Model.image?.Length > 0)
            {
                <img class="rounded " id="imgViewer" width="100" height="100" src="data:image/jpg;base64,@Convert.ToBase64String(Model.image)" />
            }
            else
            {
                <p>Not Found</p>
            }

        </div>
        <div>
            <label asp-for="Age"></label>
            <input class="form-control" asp-for="Age" />
        </div>

        @if (User.IsInRole("Admin"))
        {
            <div>
                <label asp-for="RoleId">Role</label>
                <select class="form-control" asp-for="RoleId" asp-items="roleItems"></select>
            </div>
        }

        <button type="submit" class="btn btn-primary mt-3">Edit</button>
    </form>
</div>

@section Scripts 
{ 
    <partial name="_ValidationScriptsPartial" />
    <script type="text/javascript">
        $("#fileInput").change(function (event) {
            var files = event.target.files;
            $("#imgViewer").attr("src", window.URL.createObjectURL(files[0]));
        });

        //$("#btnSave").click(function () {
        //    var files = $("#txtViewer").prop("files");
        //    var formData = new FormData();
        //    for (var i = 0; i < files.lenght; i++) {
        //        formData.append("fileInput", files[i]);
        //    }
        //    $.ajax({
        //        type: 'GET',
        //        success: function (data) {
        //            $("#imgViewer").attr("src", "data:image/jpg;base64," + data.image + "")
        //        }
        //    })
        //})
    </script>
}


    

Education/Views/Instructor/Index.cshtml
@using Education.Models
@model IEnumerable<Instructor>
@{
    ViewData["Title"] = "Index";
}

<div class="main-panel">
    <a asp-action="New" class="btn btn-primary d-flex align-self-end mb-4">Add</a>
    <table class="table table-bordered table-hover " >
        <tr class="text-center bg-primary text-light">
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Age</th>
            <th>Image</th>
            <th>Action</th>

        </tr>
        @foreach (var item in Model ?? Enumerable.Empty<Instructor>())
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Email</td>
                <td>@item.Phone</td>
                <td>@item.Address</td>
                <td>@item.Age</td>
                <td style="width:15%">
                    @if (item.image?.Length > 0)
                    {
                        <img class="w-50" src="data:image/jpg;base64,@Convert.ToBase64String(item.image)" />
                    }
                    else
                    {
                        <p>No Image</p>
                    }
                </td>
         
                <td>

                    <a class="text-success mr-3 editlink" id="edit" asp-action="Edit" asp-route-id="@item.Id">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill=" rgb(94, 94, 233)" class="bi bi-pen-fill" viewBox="0 0 16 16">
                            <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z" />
                        </svg>
                    </a>

                    <a style="background-color:#f8f9fc;border:none;" class="delete-button" data-id="@item.Id">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="red" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                            <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z" />
                        </svg>
                    </a>
                 
                </td>

            </tr>
        }
    </table>
</div>

@section Scripts
    {
    <partial name="_ValidationScriptsPartial" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/AlertifyJS/1.13.1/alertify.min.js" integrity="sha512-JnjG+Wt53GspUQXQhc+c4j8SBERsgJAoHeehagKHlxQN+MtCCmFDghX9/AcbkkNRZptyZU4zC8utK59M5L45Iw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/AlertifyJS/1.13.1/css/alertify.min.css" integrity="sha512-IXuoq1aFd2wXs4NqGskwX2Vb+I8UJ+tGJEu/Dc0zwLNKeQ7CW3Sr6v0yU3z5OQWe3eScVIkER4J9L7byrgR/fA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script>
        $(document).ready(function () {
            $(".delete-button").click(function () {
                var InstructorId = $(this).data("id");
                var deleteUrl = '@Url.Action("Delete", "Instructor", new { id = "__id__" })'.replace('__id__', InstructorId);

                alertify.confirm("Confirm Deletion", "Are you sure you want to delete this Instrucor ?",
                    function () {
                        window.location.href = deleteUrl;
                        alertify.success('Ok');
                    },
                    function () {
                        alertify.error('Cancel');
                    });
            });
        });
    </script>

}

Education/Views/Instructor/New.cshtml
@using Education.Models
@model Instructor
@{
    ViewData["Title"] = "New";
    //Layout = "_Layout";
    SelectList roleItems = new SelectList(ViewBag.RoleList, "Id", "Name");
}
<div class="main-panel">
    <form method="post" enctype="multipart/form-data">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div>
            <label asp-for="Name"></label>
            <input class="form-control" asp-for="Name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Email"></label>
            <input class="form-control" asp-for="Email" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Password"></label>
            <input class="form-control" asp-for="Password" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="confirmPassword"></label>
            <input class="form-control" asp-for="confirmPassword" />
            <span asp-validation-for="confirmPassword" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Phone"></label>
            <input class="form-control" asp-for="Phone" />
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Address"></label>
            <input class="form-control" asp-for="Address" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div>
            <!--
            <label asp-for="Age"></label>
            <input class="form-control" asp-for="Age" />
            <span asp-validation-for="Age" class="text-danger"></span>
            -->
            <label asp-for="image"></label>
            <input id="txtViewer" type="file" value="Upload Image" class="form-control mb-4" asp-for="image" />
            <img class="rounded " id="imgViewer" width="100" height="100" />
        </div>
        <div>
            <label asp-for="Age"></label>
            <input class="form-control" asp-for="Age" />
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="RoleId">Role</label>
            <select class="form-control" asp-for="RoleId" asp-items="roleItems"></select>
        </div>
        <div class="mt-4">
            <input type="submit" value="Create" class="btn btn-primary" id="btnSave" />
            <a asp-action="Index" class="btn btn-primary">Back to List</a>
        </div>

    </form>
</div>





<partial name="_ValidationScriptsPartial" />
@section Scripts
{

<script type="text/javascript">
    $("#txtViewer").change(function(event){
        var files=event.target.files;
        $("#imgViewer").attr("src",window.URL.createObjectURL(files[0]));
    });
    $("#btnSave").click(function(){
        var files = $("#txtViewer").prop("files");
        var formData=new FormData();
        for(var i=0;i<files.lenght;i++){
            formData.append("file",files[i]);
        }
        $.ajax({
            type:'GET',
            success:function(data){
                $("#imgViewer").attr("src","data:image/jpg;base64,"+data.image+"")
            }
        })
    })
</script>

 }