Education/Controllers/GradeController.cs
using Education.Models;
using Education.Repositories;
using Education.Services;
using Education.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Globalization;

namespace Education.Controllers
{
    public class GradeController : Controller
    {
        private readonly IGradeServices _GradeService;
        private readonly IStudentService _StudentService;


        public GradeController(IGradeServices GradeService, IStudentService StudentService)
        {
            _GradeService = GradeService;
            _StudentService = StudentService;
        }
        [Authorize]
        public IActionResult GetAll()
        {
            var grades = _GradeService.GetAll();
            return View(grades);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Add()
        {
            ViewBag.Students = _StudentService.GetAll().Where(s=>s.IsDeleted==false);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Add(Grade g)
        {
            var allStds = _StudentService.GetAll().Where(s => s.IsDeleted == false);
            try
            {
                if (ModelState.IsValid)
                {
                    _GradeService.Insert(g);
                    return RedirectToAction("Add");
                }
            }
            catch 
            {
                ModelState.AddModelError("studentId", "Please select Student");
            }
            if (g.studentId == 0)
            {
                ModelState.AddModelError("studentId", "Please select Student");
            }

            ViewBag.Students = allStds;
            return View(g);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Edit(int id)
        {
            ViewBag.Students = _StudentService.GetAll().Where(s => s.IsDeleted == false);
            var g = _GradeService.GetById(id);
            return View(g);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Edit(Grade g)
        {
            if (ModelState.IsValid)
            {
                _GradeService.Update(g);
                return RedirectToAction("GetAll");

            }
            ViewBag.Students = _StudentService.GetAll().Where(s => s.IsDeleted == false);
            return View();
        }


        [HttpPost]
        [Authorize]
        public IActionResult DeleteRefreshGrade(int id)
        {
            _GradeService.Delete(id);

            IEnumerable<Grade> g = _GradeService.GetAll();


            return PartialView("_AllGradePartial", g);
        }
        public IActionResult GenerateReport()
        {
            return View();
        }

            [HttpPost]
        public IActionResult GenerateReport(string selectedDate)
        {
            DateTime endDate = DateTime.ParseExact(selectedDate, "yyyy-MM-dd", CultureInfo.InvariantCulture);
            DateTime startDate = new DateTime(endDate.Year, endDate.Month, 1);
            DateTime inclusiveEndDate = endDate.AddDays(1);
            var averageNewGrades = _GradeService.GetAll()
                .Where(g => g.Date >= startDate && g.Date < inclusiveEndDate && g.Type == "New")
                .GroupBy(g => g.student.Name)
                .Select(g => new
                {
                    StudentName = g.Key,
                    AverageGrade = g.Average(s => s.grade)
                })
                .ToList();

            var averageOldGrades = _GradeService.GetAll()
                .Where(g => g.Date >= startDate && g.Date < inclusiveEndDate && g.Type == "Old")
                .GroupBy(g => g.student.Name)
                .Select(g => new
                {
                    StudentName = g.Key,
                    AverageGrade = g.Average(s => s.grade)
                })
                .ToList();

            var attendanceDays = _GradeService.GetAll()
                .Where(g => g.Date >= startDate && g.Date < inclusiveEndDate)
                .GroupBy(g => g.student.Name)
                .Select(g => new
                {
                    StudentName = g.Key,
                    AttendanceDays = g.Select(g => g.Date.Date).Distinct().Count()
                })
                .ToList();

            var reportData = averageNewGrades
                .Join(averageOldGrades, n => n.StudentName, o => o.StudentName, (n, o) => new
                {
                    StudentName = n.StudentName,
                    AverageNewGrade = n.AverageGrade,
                    AverageOldGrade = o.AverageGrade
                })
                .Join(attendanceDays, grades => grades.StudentName, attendance => attendance.StudentName, (grades, attendance) => new
                {
                    StudentName = grades.StudentName,
                    AverageNewGrade = Math.Round(grades.AverageNewGrade, 2), // Round the average grade to 2 decimal places
                    AverageOldGrade = Math.Round(grades.AverageOldGrade, 2), // Round the average grade to 2 decimal places
                    AttendanceDays = attendance.AttendanceDays
                })
                .OrderByDescending(data => data.AttendanceDays + data.AverageNewGrade + data.AverageOldGrade)
                .ToList();
            return View(reportData.Cast<dynamic>().ToList());
        }

    }
}

Education/Controllers/LessonController.cs
using Education.Enums;
using Education.Models;
using Education.Repositories;
using Education.Services;
using Education.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Security.Claims;

namespace Education.Controllers
{
    public class LessonController : Controller
    {
       
        IInstructorService instructor_repo;
        ITopicService topic_repo;
        public LessonController(IInstructorService _intructor_repo, ITopicService _topic_repo)
        {
            instructor_repo = _intructor_repo;
            topic_repo = _topic_repo;
        }
        [Authorize]
        public IActionResult Alllesson()
        {
            var lesson = topic_repo.GetAll();
            List<Lesson_infoViewModel> lesson_InfoViewModels = new List<Lesson_infoViewModel>();
            int Number = 0;

            foreach (var item in lesson)
            {
                ++Number;
                lesson_InfoViewModels.Add(new Lesson_infoViewModel()
                {
                    Number = Number,
                    Name = item.Name,
                    Date = item.Date,
                    Type = item.Type,
                    InstructorName =item.instructor.Name
                }) ;
            }
           
            return View(lesson_InfoViewModels);
        }
        [Authorize]
        public IActionResult Mylesson()
        {
            var userIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            int Id = int.Parse(userIdClaim.Value);

            var lesson = topic_repo.GetAll().Where(l=>l.InstructorId==Id);
            List<Lesson_infoViewModel> lesson_InfoViewModels = new List<Lesson_infoViewModel>();
            int Number = 0;

            foreach (var item in lesson)
            {
                ++Number;
                lesson_InfoViewModels.Add(new Lesson_infoViewModel()
                {
                    Number = Number,
                    Name = item.Name,
                    Date = item.Date,
                    Type = item.Type,
                });
            }

            return View(lesson_InfoViewModels);
        }
        [Authorize(Roles="Admin")]
        public IActionResult Addlesson()
        {
            ViewData["intructor"] = instructor_repo.GetAll();
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Addlesson(Topic topic)
        {
            if (ModelState.IsValid)
            {

                topic_repo.Insert(topic);
                return RedirectToAction("Alllesson");
            }
            ViewData["intructor"] = instructor_repo.GetAll();
            return View(topic);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Search_alllesson(DateTime date)
        {

            var lesson = topic_repo.GetAll().Where(i => i.Date.Date == date.Date).ToList();

            if (lesson.Count == 0)
            {
                TempData["NoData"] = "No data found.";
                return RedirectToAction("alllesson");
            }
            List<Lesson_infoViewModel> lesson_InfoViewModels = new List<Lesson_infoViewModel>();
            int Number = 0;

            foreach (var item in lesson)
            {
                ++Number;
                lesson_InfoViewModels.Add(new Lesson_infoViewModel()
                {
                    Number = Number,
                    Name = item.Name,
                    Date = item.Date,
                    Type = item.Type,
                    InstructorName = item.instructor.Name
                });
            }


            return View("alllesson", lesson_InfoViewModels);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Search_Mylesson(DateTime date)
        {

            var userIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            int Id = int.Parse(userIdClaim.Value);

            var lesson = topic_repo.GetAll().Where(l => l.InstructorId == Id && l.Date.Date == date.Date).ToList();
            if (lesson.Count == 0)
            {
                TempData["NoData"] = "No data found.";
                return RedirectToAction("mylesson");
            }
            List<Lesson_infoViewModel> lesson_InfoViewModels = new List<Lesson_infoViewModel>();

            int Number = 0;

            foreach (var item in lesson)
            {
                ++Number;
                lesson_InfoViewModels.Add(new Lesson_infoViewModel()
                {
                    Number = Number,
                    Name = item.Name,
                    Date = item.Date,
                    Type = item.Type,
                });
            }

            return View("mylesson", lesson_InfoViewModels);
        }
    }
}

Education/Controllers/StudentController.cs
using AutoMapper;
using Education.Models;
using Education.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Data;
using System.Security.Claims;

namespace Education.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService _studentService;
        private readonly INewStudentService _NewStudentService;
        private readonly IRequestsServices _studentRequestService;
        private readonly IMapper _imapper;
        
       

        public StudentController(IStudentService studentService, INewStudentService NewStudentService, IRequestsServices studentRequestService,IMapper imapper)
        {
            _studentService = studentService;
            _NewStudentService= NewStudentService;
            _studentRequestService= studentRequestService;
            _imapper = imapper;


        }
        [Authorize]
        public IActionResult Index()
        {
            List<Student> students = _studentService.GetAll().Where(s=>s.confirm== "accepted" && s.IsDeleted==false).ToList();
            
            return View(students);
        }
        [Authorize]
        public IActionResult New()
        {
            ViewBag.EditButtonValue = "Create";
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult New(Student student, IFormFile? ImageFile)
        {
            var userIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            int Id = int.Parse(userIdClaim.Value);

            ViewBag.EditButtonValue = "Create";

            ModelState.Remove("confirm");
            if (ModelState.IsValid)
            {
                try
                {
                    if (ImageFile != null && ImageFile.Length > 0)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            ImageFile.CopyTo(memoryStream);
                            student.image = memoryStream.ToArray();
                        }
                    }

                 
                    if (User.IsInRole("Admin"))
                    {

                        student.confirm = "accepted";
                        _studentService.Insert(student);
                    }
                    else
                    {
                        student.confirm = "pending";
                        _studentService.Insert(student);
                        StudentRequests studentRequest = new StudentRequests()
                        {
                            StudentId = student.Id,
                            InstructorId = Id,
                            Status = "pending",
                            OperationType = "add"
                        };
                        _studentRequestService.insert(studentRequest);
                    }
                    return RedirectToAction("New");

                }catch(Exception ex)
                {
                    ModelState.AddModelError("", ex.InnerException.Message);
                }
            }

            return View(student);

        }
        [Authorize]
        public IActionResult Remove(int id)
        {
            var userIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            int Id = int.Parse(userIdClaim.Value);
            if (User.IsInRole("Admin"))
            {
                _studentService.Delete(id);
            }else
            {
                Student student=_studentService.GetById(id);
                if(student!=null)
                {
                    StudentRequests studentRequest = new StudentRequests()
                    {
                        StudentId = student.Id,
                        
                        InstructorId = Id,
                        Status = "pending",
                        OperationType = "delete"
                    };
                  
                    StudentRequests ExisitingRequest = _studentRequestService.GetAllRequestInfo().FirstOrDefault(r => r.StudentId == student.Id && r.OperationType == "delete");
                    if(ExisitingRequest==null)
                    {
                        _studentRequestService.insert(studentRequest);
                    }
                   
                }
               
            }
          

            return RedirectToAction("index");

        }
        [Authorize]
        public IActionResult Edit(int id)
        {
            ViewBag.EditButtonValue = "Edit";
            Student student = _studentService.GetById(id);

           
            return View("New",student);

        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize]
        public IActionResult Edit(Student student,IFormFile? ImageFile)
        {
            var userIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            int Id = int.Parse(userIdClaim.Value);
            ViewBag.EditButtonValue = "Edit";
            ModelState.Remove("confirm");
            if (ModelState.IsValid)
            {
                try
                {
                    if (ImageFile != null && ImageFile.Length > 0)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            ImageFile.CopyTo(memoryStream);
                            student.image = memoryStream.ToArray();
                        }
                    }
                    else
                    {
                        
                        student.image = _studentService.GetByIdAsNoTracking(student.Id).image;

                    }

                    if (User.IsInRole("Admin"))
                    {
                    student.confirm = "accepted";

                        _studentService.Update(student);
                    }else
                    {
                        
                        StudentRequests studentRequest = new StudentRequests()
                        {
                            StudentId = student.Id,
                            InstructorId = Id,
                            Status = "pending",
                            OperationType = "edit"
                        };
                        _studentRequestService.insert(studentRequest);
                        var requestId=studentRequest.Id;
                      
                        var newStudentData=  _imapper.Map<NewStudentData>(student);
                         newStudentData.StudentReqId=requestId;

                        _NewStudentService.insert(newStudentData);
                      
                    }
                   
                    
                }catch(Exception ex)
                {
                    ModelState.AddModelError("", ex.InnerException.Message);
                }
                return RedirectToAction("Index");
            }
            
            return View("New", student);

        }

    }
}

Education/Views/Shared/_ImagePartial.cshtml
@model string;
<img class="img-profile rounded-circle" src="@Model" alt="Student Image"  />

Education/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Education</title>

   
    <link href="/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"  rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.4.0/css/all.css">
  
    <link href="/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="/css/ProfileStyle.css" rel="stylesheet" />
    <link rel="stylesheet" href="/css/feather.css">
    <link rel="stylesheet" href="/css/Dashbord.css">


</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/Home/Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>

                </div>
                <div class="sidebar-brand-text mx-3"> Education</div>
            </a>

            <hr class="sidebar-divider my-0">
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Home">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link collapsed "  data-target="#collapseTwo"  aria-expanded="true" aria-controls="collapseTwo" asp-area="" asp-controller="Student" asp-action="Index">

                    
                    <span style="font-size: 0.9em;">Students</span>
                </a>
               
            </li>
           
              @if(User.IsInRole("Admin"))
            {
                <hr class="sidebar-divider">
                <li class="nav-item">
                    <a class="nav-link collapsed " data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo" asp-area="" asp-controller="instructor" asp-action="Index">


                        <span style="font-size: 0.9em;">Instructors</span>
                    </a>

                </li>
            }
           
            <hr class="sidebar-divider">

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Assgined"  aria-expanded="true" aria-controls="collapseUtilities">
         
                    <span style="font-size: 0.9em;">Lessons</span>
                </a>
                <div id="Assgined" class="collapse" aria-labelledby="headingUtilities"   data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-action="Mylesson" asp-controller="Lesson" asp-area="" >My Lesson</a>
                        <a class="collapse-item" asp-action="Alllesson" asp-controller="Lesson" asp-area="">All Lessons</a>
                    </div>
                </div>
            </li>


            <hr class="sidebar-divider">

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Grades"   aria-expanded="true" aria-controls="collapseUtilities">
              
                    <span style="font-size: 0.9em;">Grades</span>
                </a>
                <div id="Grades" class="collapse" aria-labelledby="headingUtilities"  data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-action="GetAll" asp-controller="Grade">Show Grades</a>
                        <a class="collapse-item" asp-action="Add" asp-controller="Grade">Add Grade</a>
                    </div>
                </div>
            </li>

            <hr class="sidebar-divider">



            <li class="nav-item">
                <a class="nav-link  "  aria-expanded="true" aria-controls="collapseTwo" asp-controller="Requests" asp-action="ViewAllRequests">
                    <span style="font-size: 0.9em;">Requests</span>
                </a>

            </li>
           


            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link "data-target="#re" aria-expanded="true" aria-controls="collapseUtilities" asp-action="GenerateReport" asp-controller="Grade">
                 
                    <span style="font-size: 0.9em;">Reports</span>
                </a>
             
            </li>


            <hr class="sidebar-divider d-none d-md-block">


        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">


                    <!-- Sidebar Toggle (Topbar) -->


                    <button id="sidebarToggleTop" class="btn btn-link  rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.Identity.Name</span>
                                <div id="imgDis"> </div>
                                     
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item"  asp-controller="Account" asp-action="Profile">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>

                                <a class="dropdown-item" asp-controller="Account" asp-action="ChangePassword">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Change Password
                                </a>

                                <a class="dropdown-item"  asp-controller="Account" asp-action="LogOut">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                                
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid d-flex flex-column">
                    @RenderBody()




                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
           

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"   aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="/vendor/jquery.min.js"></script>
    <script src="/vendor/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/vendor/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        function updateUserImage() {
            $.ajax({
                url: '/Instructor/ShowImage',
                type: 'GET',
                success: function (data) {
                    var div = document.getElementById("imgDis");
                    div.innerHTML = data;
                }
            });
        }

        $(document).ready(function () {
            updateUserImage();
        });
    </script>
</body>

</html>

Education/Views/Shared/_ProfileLayout.cshtml
<div class="container">
    <div class="main-body">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                            <div class="mt-3">
                                <h4>John Doe</h4>
                                <p class="text-secondary mb-1">Role:Admin</p>
                                <p class="text-muted font-size-sm">Address</p>
                                <button class="btn btn-primary">Back</button>
                                <button class="btn btn-outline-primary">Edit</button>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Full Name</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                Kenneth Valdez
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Role</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                Admin
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                fip@jukmuh.al
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Phone</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                (239) 816-9029
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Age</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                12 years old
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Address</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                Bay Area, San Francisco, CA
                            </div>
                        </div>


                    </div>
                </div>




            </div>
        </div>

    </div>
</div>/html>